name          = "App-optex"
readme_from   = "script/optex"
abstract_from = "script/optex"
script_files  = [ "script/optex" ]
authority     = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"

[unsupported]
os = [
    "MSWin32",
]

[FileGatherer]
exclude_match = [
    '^CLAUDE\.md$',
    '^\.claude/',
]

[release]
branch = 'master'
hooks = [
    "make -C docs",
]
